# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Program

# Model Form Field configuration
form: $/umar/organization/models/program/fields.yaml

# Model Class name
modelClass: UMAR\Organization\Models\Program

# Default redirect location
defaultRedirect: umar/organization/programs

# Create page
create:
    title: Create Program
    redirect: umar/organization/programs/update/:id
    redirectClose: umar/organization/programs

# Update page
update:
    title: Edit Program
    redirect: umar/organization/programs
    redirectClose: umar/organization/programs

# Preview page
preview:
    title: Preview Program