# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Status

# Model Form Field configuration
form: $/umar/organization/models/status/fields.yaml

# Model Class name
modelClass: UMAR\Organization\Models\Status

# Default redirect location
defaultRedirect: umar/organization/status

# Create page
create:
    title: Create Status
    redirect: umar/organization/status/update/:id
    redirectClose: umar/organization/status

# Update page
update:
    title: Edit Status
    redirect: umar/organization/status
    redirectClose: umar/organization/status

# Preview page
preview:
    title: Preview Status