# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Setting

# Model Form Field configuration
form: $/umar/organization/models/setting/fields.yaml

# Model Class name
modelClass: UMAR\Organization\Models\Setting

# Default redirect location
defaultRedirect: umar/organization/settings

# Create page
create:
    title: Create Setting
    redirect: umar/organization/settings/update/:id
    redirectClose: umar/organization/settings

# Update page
update:
    title: Edit Setting
    redirect: umar/organization/settings
    redirectClose: umar/organization/settings

# Preview page
preview:
    title: Preview Setting