# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Testimonial

# Model Form Field configuration
form: $/umar/organization/models/testimonial/fields.yaml

# Model Class name
modelClass: UMAR\Organization\Models\Testimonial

# Default redirect location
defaultRedirect: umar/organization/testimonials

# Create page
create:
    title: Create Testimonial
    redirect: umar/organization/testimonials/update/:id
    redirectClose: umar/organization/testimonials

# Update page
update:
    title: Edit Testimonial
    redirect: umar/organization/testimonials
    redirectClose: umar/organization/testimonials

# Preview page
preview:
    title: Preview Testimonial